# Generated by Django 5.0.6 on 2024-08-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_job_jobs_delete_drinks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
